<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Permission;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            // System permissions
            [
                'module' => 'system',
                'resource' => 'users',
                'action' => 'create',
                'scope' => 'all',
                'display_name' => 'Create Users',
                'description' => 'Create new users in the system',
                'is_system_permission' => true,
            ],
            [
                'module' => 'system',
                'resource' => 'users',
                'action' => 'read',
                'scope' => 'all',
                'display_name' => 'View All Users',
                'description' => 'View all users in the system',
                'is_system_permission' => true,
            ],
            [
                'module' => 'system',
                'resource' => 'users',
                'action' => 'read',
                'scope' => 'department',
                'display_name' => 'View Department Users',
                'description' => 'View users in same department',
                'is_system_permission' => true,
            ],
            [
                'module' => 'system',
                'resource' => 'users',
                'action' => 'read',
                'scope' => 'own',
                'display_name' => 'View Own Profile',
                'description' => 'View own user profile',
                'is_system_permission' => true,
            ],
            [
                'module' => 'system',
                'resource' => 'users',
                'action' => 'update',
                'scope' => 'all',
                'display_name' => 'Update All Users',
                'description' => 'Update any user in the system',
                'is_system_permission' => true,
            ],
            [
                'module' => 'system',
                'resource' => 'users',
                'action' => 'update',
                'scope' => 'own',
                'display_name' => 'Update Own Profile',
                'description' => 'Update own user profile',
                'is_system_permission' => true,
            ],
            [
                'module' => 'system',
                'resource' => 'users',
                'action' => 'delete',
                'scope' => 'all',
                'display_name' => 'Delete Users',
                'description' => 'Delete users from the system',
                'is_system_permission' => true,
            ],
            [
                'module' => 'system',
                'resource' => 'roles',
                'action' => 'manage',
                'scope' => 'all',
                'display_name' => 'Manage Roles',
                'description' => 'Create, update, delete roles',
                'is_system_permission' => true,
            ],
            [
                'module' => 'system',
                'resource' => 'permissions',
                'action' => 'manage',
                'scope' => 'all',
                'display_name' => 'Manage Permissions',
                'description' => 'Create, update, delete permissions',
                'is_system_permission' => true,
            ],
            [
                'module' => 'system',
                'resource' => 'organizations',
                'action' => 'manage',
                'scope' => 'all',
                'display_name' => 'Manage Organizations',
                'description' => 'Create, update, delete organizations',
                'is_system_permission' => true,
            ],
            [
                'module' => 'system',
                'resource' => 'departments',
                'action' => 'manage',
                'scope' => 'all',
                'display_name' => 'Manage All Departments',
                'description' => 'Create, update, delete any department',
                'is_system_permission' => true,
            ],
            [
                'module' => 'system',
                'resource' => 'departments',
                'action' => 'manage',
                'scope' => 'own',
                'display_name' => 'Manage Own Department',
                'description' => 'Manage own department',
                'is_system_permission' => true,
            ],
            [
                'module' => 'system',
                'resource' => 'audit_logs',
                'action' => 'read',
                'scope' => 'all',
                'display_name' => 'View All Audit Logs',
                'description' => 'View all system audit logs',
                'is_system_permission' => true,
            ],

            // Work module permissions
            [
                'module' => 'work',
                'resource' => 'tasks',
                'action' => 'create',
                'scope' => 'all',
                'display_name' => 'Create Tasks',
                'description' => 'Create new tasks',
                'is_system_permission' => false,
            ],
            [
                'module' => 'work',
                'resource' => 'tasks',
                'action' => 'read',
                'scope' => 'all',
                'display_name' => 'View All Tasks',
                'description' => 'View all tasks in the system',
                'is_system_permission' => false,
            ],
            [
                'module' => 'work',
                'resource' => 'tasks',
                'action' => 'read',
                'scope' => 'department',
                'display_name' => 'View Department Tasks',
                'description' => 'View tasks in same department',
                'is_system_permission' => false,
            ],
            [
                'module' => 'work',
                'resource' => 'tasks',
                'action' => 'read',
                'scope' => 'own',
                'display_name' => 'View Own Tasks',
                'description' => 'View own assigned tasks',
                'is_system_permission' => false,
            ],
            [
                'module' => 'work',
                'resource' => 'tasks',
                'action' => 'update',
                'scope' => 'all',
                'display_name' => 'Update All Tasks',
                'description' => 'Update any task in the system',
                'is_system_permission' => false,
            ],
            [
                'module' => 'work',
                'resource' => 'tasks',
                'action' => 'update',
                'scope' => 'own',
                'display_name' => 'Update Own Tasks',
                'description' => 'Update own assigned tasks',
                'is_system_permission' => false,
            ],
            [
                'module' => 'work',
                'resource' => 'tasks',
                'action' => 'delete',
                'scope' => 'all',
                'display_name' => 'Delete Tasks',
                'description' => 'Delete any task in the system',
                'is_system_permission' => false,
            ],
            [
                'module' => 'work',
                'resource' => 'projects',
                'action' => 'create',
                'scope' => 'all',
                'display_name' => 'Create Projects',
                'description' => 'Create new projects',
                'is_system_permission' => false,
            ],
            [
                'module' => 'work',
                'resource' => 'projects',
                'action' => 'read',
                'scope' => 'all',
                'display_name' => 'View All Projects',
                'description' => 'View all projects in the system',
                'is_system_permission' => false,
            ],
            [
                'module' => 'work',
                'resource' => 'projects',
                'action' => 'update',
                'scope' => 'all',
                'display_name' => 'Update Projects',
                'description' => 'Update any project in the system',
                'is_system_permission' => false,
            ],
            [
                'module' => 'work',
                'resource' => 'projects',
                'action' => 'delete',
                'scope' => 'all',
                'display_name' => 'Delete Projects',
                'description' => 'Delete any project in the system',
                'is_system_permission' => false,
            ],

            // HRM module permissions
            [
                'module' => 'hrm',
                'resource' => 'employees',
                'action' => 'create',
                'scope' => 'all',
                'display_name' => 'Create Employees',
                'description' => 'Create new employee records',
                'is_system_permission' => false,
            ],
            [
                'module' => 'hrm',
                'resource' => 'employees',
                'action' => 'read',
                'scope' => 'all',
                'display_name' => 'View All Employees',
                'description' => 'View all employee records',
                'is_system_permission' => false,
            ],
            [
                'module' => 'hrm',
                'resource' => 'employees',
                'action' => 'update',
                'scope' => 'all',
                'display_name' => 'Update Employee Records',
                'description' => 'Update any employee record',
                'is_system_permission' => false,
            ],
            [
                'module' => 'hrm',
                'resource' => 'attendance',
                'action' => 'manage',
                'scope' => 'all',
                'display_name' => 'Manage Attendance',
                'description' => 'Manage employee attendance records',
                'is_system_permission' => false,
            ],
            [
                'module' => 'hrm',
                'resource' => 'payroll',
                'action' => 'manage',
                'scope' => 'all',
                'display_name' => 'Manage Payroll',
                'description' => 'Manage employee payroll',
                'is_system_permission' => false,
            ],

            // CRM module permissions
            [
                'module' => 'crm',
                'resource' => 'customers',
                'action' => 'create',
                'scope' => 'all',
                'display_name' => 'Create Customers',
                'description' => 'Create new customer records',
                'is_system_permission' => false,
            ],
            [
                'module' => 'crm',
                'resource' => 'customers',
                'action' => 'read',
                'scope' => 'all',
                'display_name' => 'View All Customers',
                'description' => 'View all customer records',
                'is_system_permission' => false,
            ],
            [
                'module' => 'crm',
                'resource' => 'leads',
                'action' => 'manage',
                'scope' => 'all',
                'display_name' => 'Manage Leads',
                'description' => 'Manage customer leads',
                'is_system_permission' => false,
            ],
            [
                'module' => 'crm',
                'resource' => 'deals',
                'action' => 'manage',
                'scope' => 'all',
                'display_name' => 'Manage Deals',
                'description' => 'Manage sales deals',
                'is_system_permission' => false,
            ],

            // Warehouse module permissions
            [
                'module' => 'warehouse',
                'resource' => 'products',
                'action' => 'create',
                'scope' => 'all',
                'display_name' => 'Create Products',
                'description' => 'Create new products',
                'is_system_permission' => false,
            ],
            [
                'module' => 'warehouse',
                'resource' => 'products',
                'action' => 'read',
                'scope' => 'all',
                'display_name' => 'View All Products',
                'description' => 'View all products',
                'is_system_permission' => false,
            ],
            [
                'module' => 'warehouse',
                'resource' => 'inventory',
                'action' => 'manage',
                'scope' => 'all',
                'display_name' => 'Manage Inventory',
                'description' => 'Manage product inventory',
                'is_system_permission' => false,
            ],
            [
                'module' => 'warehouse',
                'resource' => 'orders',
                'action' => 'manage',
                'scope' => 'all',
                'display_name' => 'Manage Orders',
                'description' => 'Manage customer orders',
                'is_system_permission' => false,
            ],
        ];

        foreach ($permissions as $permission) {
            Permission::create($permission);
        }
    }
}
